#!/bin/bash
# Describe gallery images using Ollama vision model
# Usage: ./scripts/describe-gallery.sh [model]
# Output: YAML-formatted image descriptions to stdout

MODEL="${1:-gemma3:27b}"
IMG_DIR="img/aaai-26"
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo "# Generated by describe-gallery.sh using $MODEL"
echo "# $(date -Iseconds)"
echo ""

for img in "$SCRIPT_DIR/$IMG_DIR"/*.jpeg; do
  filename="$(basename "$img")"
  echo "Processing: $filename" >&2

  response=$(ollama run "$MODEL" "You are analyzing a photo from the AAAI 2026 AI conference in Singapore. Respond in EXACTLY this format with no other text:

alt: <concise alt text for accessibility, 10-15 words>
description: <1-2 sentence description of what's in the photo>
tags: <comma-separated labels, 3-6 tags>

Describe what you see." "$img" 2>/dev/null)

  # Parse response lines
  alt=$(echo "$response" | grep -i '^alt:' | head -1 | sed 's/^[Aa]lt: *//')
  description=$(echo "$response" | grep -i '^description:' | head -1 | sed 's/^[Dd]escription: *//')
  tags=$(echo "$response" | grep -i '^tags:' | head -1 | sed 's/^[Tt]ags: *//')

  # Fallbacks if parsing fails
  [ -z "$alt" ] && alt="AAAI-26 conference photo"
  [ -z "$description" ] && description=""
  [ -z "$tags" ] && tags=""

  cat <<EOF
- file: "$filename"
  alt: "$alt"
  description: "$description"
  tags: "$tags"

EOF
done

echo "Done!" >&2
